### ISSUE TITLE
LMDB Issue

### ISSUE THREAD

**Issue by joshuasteier** [sophos-ai/SOREL-20M#17]
Hello,
After training the neural network model, I moved to the evaluation with evaluate.py:
python evaluate.py evaluate_network /home/ubuntu/results/0 /home/ubuntu/SOREL-20M1/checkpoints/epoch_9.pt.

I get the following error:

Traceback (most recent call last):
  File "evaluate.py", line 134, in <module>
    baker.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/baker.py", line 888, in run
    value = self.apply(*self.parse(argv), instance=instance)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/baker.py", line 866, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "evaluate.py", line 86, in evaluate_network
    for shas, features, labels in tqdm.tqdm(generator):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1119, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
lmdb.InvalidParameterError: Caught InvalidParameterError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/SOREL-20M/dataset.py", line 145, in __getitem__
    features = self.features_lmdb_reader(key)
  File "/home/ubuntu/SOREL-20M/dataset.py", line 30, in __call__
    with self.env.begin() as txn:
lmdb.InvalidParameterError: mdb_txn_begin: Invalid argument

  I'm not sure what is causing this and I would be grateful for any tips.

**Comment by mashalzainab** [comment]
I have the same issue, did you find a solution?
